### PR TITLE
PMM-13566 Add Makefile to simplfy the build process.

### PR DESCRIPTION
**Pull request by talhabinrizwan**
PMM-13566

### CODE REVIEW

**Review by BupycHuk — APPROVED** [review]

**Comment by BupycHuk** [comment]
I used to use following command from CONTRIBUTING.MD
```docker build . -f dockerfiles/Dockerfile.dev-self-contained -t perconalab/watchtower:dev-latest```

**Comment by talhabinrizwan** [comment]
> I used to use following command from CONTRIBUTING.MD `docker build . -f dockerfiles/Dockerfile.dev-self-contained -t perconalab/watchtower:dev-latest`

Initially, I considered the same approach, but I realized that the build command needs to be executed inside the `public.ecr.aws/e7j3v3n0/rpmbuild:3` container. This is because our Jenkins agents, such as `agent-amd64-ol9`, do not have the Go compiler toolchain installed. Therefore, I separated the build process from the docker build step.

**Review by ademidoff — APPROVED** [review]

**Comment by BupycHuk** [comment]
@talhabinrizwan why it's needed to be run inside rpmbuild:3? that command runs go commands in docker as well.

**Comment by talhabinrizwan** [comment]
> @talhabinrizwan why it's needed to be run inside rpmbuild:3? that command runs go commands in docker as well.

We're already running go command inside docker. I was referring  to `rpmbuild:3` image we are using to build it. 
Please also check https://github.com/Percona-Lab/jenkins-pipelines/pull/3071

**Pull request merged**
